AtomLinter/linter-eslint

lib/linter-eslint.coffee
package.json

ESLint 0.13.0 added support for JSX and some ES6 features. This is important because it obsoletes JSXHint which is soon going to be sunset.

Upgrade to eslint 0.13.0

---

package.json

Update to eslint `^0.14.0`, which adds predefined [Meteor](http://meteor.com) globals.

Support predefined Meteor globals (update eslint dependency)

---

README.md
lib/linter-eslint.coffee
package.json

Fixes https://github.com/AtomLinter/linter-eslint/issues/21
Fixes https://github.com/AtomLinter/linter-eslint/issues/26
[resolve](https://www.npmjs.com/package/resolve)
> implements the node require.resolve() algorithm such that you can require.resolve() on behalf of a file asynchronously and synchronously
This branch will find and load the eslint that is local to the project you're working on if it's available. If none is found it just falls back to the one packaged in `linter-eslint`. I did notice that it doesn't find a globally installed eslint. I'm new to Atom, but I suspect it's because this this runs from inside atom instead of from node.
This is the same technique that [grunt-cli](https://github.com/gruntjs/grunt-cli/blob/master/bin/grunt#L33) uses to load your local version of …

Use resolve to locate a local version of eslint

---

lib/linter-eslint.coffee

If you use any of the new es6 syntax that isn't supported by eslint (or isn't turned on) you get a confusing looking message like `Unexpected reserved word (undefined)`. It took me a few times seeing that to figure out what that `undefined` was all about.

Improve messaging for fatal errors

---

lib/linter-eslint.coffee

The `.eslintignore` settings do not work on Windows because the relative path construction assumes the path separator is always forward-slash while Windows uses a backslash.

Fix ignorePath on Windows

---

package.json

Fixes error with `space-before-function-paren` that was added in the release on March 28. 
This fix resolved the error I was having locally

upgrading to eslint 0.18.0. Resolves AtomLinter/linter-eslint#50

---

lib/linter-eslint.coffee

Fixing issue #54 according to deprecation message:
> Config::unobserve no longer does anything. Call .dispose() on the object returned by Config::observe instead.

Fixing issue #54; Config.unobserve is deprecated.

---

package.json

Kills a Deprecation Cop warning.
activationEvents has been deprecated since v0.153.0:
https://github.com/atom/atom/commit/53b538311e85b2539e8709ef8dd44d8ab74e
9bab

Use activationCommands instead of activationEvents.

---

lib/linter-eslint.coffee

This adds support for the `source.babel` syntax, provided by the package [language-babel](https://atom.io/packages/language-babel).

Support `source.babel` syntax

---

lib/linter-eslint.coffee

Fixes #74 and have to fix #72 also.
It needs somewhere to warn users about the versin `linter-eslint` with this patch
works only with `eslint@0.21`+

Fix for eslint@0.21. Use addPlugin() method.

---

lib/linter-eslint.coffee

Many people use the [language-javascript-semantic](https://github.com/p-e-w/language-javascript-semantic) package in combination with this linter plugin. If we could have baked in support for the grammar in this plugin it would save the hassle of having to re-add it whenever the plugin updates.

Adds semantic javascript to supported grammars

---

lib/linter-eslint.coffee

Current version does not loads plugins from global packages properly. This PR fixes this problem.

Fix loading plugins while using global npm path

---

README.md
lib/linter-eslint.coffee

I have added a config option 'showRuleIdInMessage', that when set to
true will add the corresponding eslint rule id to warning/error
messages. Config option is default false.

Add config option to show eslint ruleid in messages

---

lib/linter-eslint.coffee

Hi, you use `fs` package on [L75](https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.coffee#L75) and it not properly requered, so i get "fs is not defined" error.

Fix "fs is not defined" on linting

---

lib/linter-eslint.js

This tells linter-eslint to recursively search parent directories for the eslint binary. This supports projects that share a eslint configuration between multiple subprojects:
```
.
├── Client
│   ├── client.js
│   └── package.json
├── Server
│   ├── server.js
│   └── package.json
└── package.json  # eslint, babel-eslint, eslint-plugins here
```
With this commit, if you open up the Client or Server directory in Atom, linter-eslint will find eslint in the parent directory's node_modules.
There was also a bug where setting `this.binary` would add a property to the global object instead of the exports, since `findESLint` was using unbound functions. Switched to arrow functions to fix this.

Search for eslint in parent directories and fix `this.binary` caching

---

lib/linter-eslint.js

This PR ensures the correct platform path separators are used.
Using incorrect separators causes at least [these lines](https://github.com/AtomLinter/linter-eslint/blob/master/lib/linter-eslint.js#L112-L113) to not replace the `cwd` from the file path and therefore on Windows `linter-eslint` always passes the full path to ESLint causing `.eslintignore` logic to fail.

[2.3.0 on Windows] .eslintignore not being honored

---

lib/linter-eslint.coffee

This pull request fixes some minor typos in error messages and one in the useGlobalEslint setting description.

Fix minor typos in help/error messages

---

lib/linter-eslint.coffee

This lets users open up subdirectories of their project and still use their project's copy of eslint. For example:
```
project/
subdir/
src.js
node_modules/
eslint/
```
If you open `subdir` in Atom, linter-eslint will now load `project/node_modules/eslint`.

Search up the directory hierarchy for the local copy of eslint

---

lib/linter-eslint.coffee

eslint 1.0.0-rc-2 uses `Function` inside one of its dependencies. This causes an error in Atom because Atom uses CSP to prevent `Function` from working. To work around this, we need to use `loophole.allowUnsafeNewFunction` once a PR I submitted to `loophole` is merged.
Partly fixes #177.

Wrap `require('eslint')` in `allowUnsafeNewFunction`

---

package.json

This makes sure that all users of linter-eslint are using loophole 1.1.0 which works with eslint 1.0 RC2.

Update `loophole` to 1.1.0 so that it works with eslint 1.0.0-rc-2

---

README.md
lib/linter-eslint.coffee
package.json

Automatically install the `linter` package, if it is not already. Remove the requirement that it be loaded to allow the use of an alternative consumer of this provider.
Closes #207.
Closes #212.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/217)

Auto install linter

---

lib/linter-eslint.coffee

Specifies the linter name, allowing the linter package to display it if the user chooses to.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/222)

Add linter name

---

lib/linter-eslint.coffee

"error" and "warning" should be "Error" and "Warning" as per the official linter spec. (see https://github.com/atom-community/linter/wiki/Linter-API, in particular https://github.com/atom-community/linter/wiki/Registering-Custom-Message-Types)
This doesn't normally matter, but other consumers of the API (at the moment, namely Nuclide's diagnostics plugin) might be sensitive to the distinction.

Capitalize types of linter messages

---

lib/linter-eslint.coffee

Fix for #239.
The linter package will still display the html , but other packages that consume linter messages can choose between using either html or text as shown below.
For the text I made it follow this convention: ruleId - message. Does this work or would you prefer it be formatted in a different way?

Added text property to errors

---

lib/linter-eslint.coffee
package.json

#194 Use [executeOnText](http://eslint.org/docs/developer-guide/nodejs-api.html#executeontext) instead of [linter](http://eslint.org/docs/developer-guide/nodejs-api.html#linter) because `linter` does not support [plugin](https://github.com/BenoitZugmeyer/eslint-plugin-html)

Lint javascript inside HTML file

---

lib/linter-eslint.coffee

Reverts AtomLinter/linter-eslint#240
It's a fatal error in latest linter as it's an abuse of the API
Ref: https://github.com/atom-community/linter/pull/975

Revert "Added text property to errors"

---

lib/linter-eslint.coffee

`pipe` should be the default option in `execSync`, but it seems it is not the case.
https://nodejs.org/api/child_process.html#child_process_options_stdio
Closes #244

Fix Error: EPERM: on Windows box

---

CHANGELOG.md
lib/worker.js

OSX has a problem that applications launched from the Dock do not inherit `$PATH`, so if somebody starts Atom from the Dock instead of Terminal and tries to use the global ESLint, we now show them a nicer notification instead of a confusing trace
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/273)

Show a nicer error if spawning NPM fails

---

lib/main.js

When the column error is the last char of the line, due to `rangeFromLineNumber`, the range is malformed: the start column is greater than the end column.
(Also const values cannot be modified) :)
See #276.

Fix wrong column offset

---

lib/main.js

The patch makes more sense if I don't use the `colStart` parameter.
Indeed the range, with zero-based column, is returned. 
Then, if the error is in the column past the last char (equals to the length of the line + 1), we need to fix accordingly colEnd (`range[1][1]`).
See #276 and #277

Improve code readable about column offset

---

CHANGELOG.md
lib/worker.js

This enhances the eslint rules dir support to allow absolute paths as well as those relative to the project.

Support local and absolute paths for eslint rules dir.

---

lib/worker.js
package.json

* :new: Interpolate environment variables in the provided path for the eslint config file
Closes #291
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/297)

Interpolate env var in conf path

---

lib/worker.js

Tiny change extending @SpainTrain's patch to include the config file path
https://github.com/SpainTrain/linter-eslint/commit/76662cd91ac90ae448faf847fb8173eba8cec19d

Extend resolveEnv support to the configFile path

---

.editorconfig
lib/worker.js

`.eslintignore` files must be placed at a project's root, and the patterns within the .eslintignore are relative to project root.  Therefore, for ESLint to know whether a file should be ignored, one of two things must be true:
1. The .eslintignore entries need to be in the format `**/foo.js`
2. The paths passed to eslint for `--stdin-filename` need to be relative to the project root, which is where the .eslintignore must be located.
This change will check for the existence of a `.eslintignore` file, and if one is found, the arguments to `--stdin-filename` will be relative to its directory.
It also adds an `.editorconfig` file to the repo, to make it easier for contributors to use the correct style.

Use relative file paths if possible

---

CHANGELOG.md
lib/main.js
lib/worker.js

This adds a `disableWhenNoEslintConfig` setting.  When `true` (the default), the linter will be disabled only if no config is found in a `package.json` or `.eslintrc` file.
This removes the `disableWhenNoEslintrcFileInPath` setting (which breaks the use of `eslintConfig` in `package.json`).
I couldn't see an easy way to add tests for this.  Let me know if you have any suggestions.  In addition, I'd be happy to rework this if you would prefer to reuse the original setting (or keep it and add the new one).
Fixes #226.

Check for config in package.json and .eslintrc before disabling

---

lib/worker.js

The change in #319 broke the use of `find` when the second arg is a string.
Fixes #324

Fix find for use with a string arg

---

lib/main.js

Attempting to keep users from thinking that they need to wait for the `worker not initialized yet` message to go away.

Communicate worker start depends on user action

---

lib/worker.js

http://eslint.org/blog/2015/11/eslint-v1.10.0-released/
> Configuration File Formats
> v1.10.0 introduces the ability to use configuration files in different formats. Instead of the regular .eslintrc file, you can use a JavaScript (.eslintrc.js), a YAML file (.eslintrc.yml or .eslintrc.yaml), or a JSON file (.eslintrc.json). We are formally deprecating use of the .eslintrc extensionless configuration file format in favor the format-specific versions. Don't worry, we'll still support .eslintrc files for a long time, but we'd like to encourage everyone to move to the new file formats as you'll get advantages such as syntax highlighting and error detection with many editors. Read more in the documentation.

Fix .eslintrc.js

---

package.json

Limit `eslint-config-airbnb` to the 1.x.x branch, inline the contents of `eslint-config-steelbrain`.

Solidify eslint config a bit

---

circle.yml

Force updating `wget` as the current containers for some reason downgraded it and it fails to download Atom now.
Add `apm -v` output.

Update CircleCI setup

---

CHANGELOG.md
lib/worker.js

This patch fixes the exception raised applying "Fix File" command.
It doesn't follow the disruptive suggestion to assimilate on('FIX' to on('JOB' , because there are too much IF statements.
Maybe we can refactor the listeners later and in another way.
Closes #353

Fix exception for "Fix File" on Windows

---

lib/worker.js

* :bug: Check that `configFile` is a string before calling `resolveEnv` on it
Closes #356
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/358)

Check that configFile is string

---

package.json

As said in the Readme:
> Indent is 2 spaces
So why not add this as a ESLint rule?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/382)

EsLint rule: Indent two spaces

---

package.json

Reverts AtomLinter/linter-eslint#382.
We are depending on `eslint-config-airbnb`, which [already specifies](https://github.com/airbnb/javascript/blob/eslint-config-airbnb-v2.1.1/packages/eslint-config-airbnb/rules/style.js#L27) the indent rules. This PR overrode that specification with a much simpler version.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/384)

Revert "EsLint rule: Indent two spaces"

---

.gitignore
lib/es5-helpers.js
spec/fixtures/local-eslint/.gitignore

Fixes #294 and my case outlined in #350 as well. It's an improved version of #350 after some discussion, specifically, it does not rely on presence of `package.json` in sub-projects - #350 was assuming they are not defined, which seems to be only applicable to browserify projects.
It essentially works in the same way as lookup for `.eslintrc` - find the closest `node_modules/eslint` folder starting from the `fileDir` and moving up.
The feature is in lines 15-17, the rest is just styling tweaks - early return to make it easier to reason about and better scoping of variables.
Tested in failing projects with `babel-eslint` and `eslint-plugin-react` plugins.
CC: @Arcanemagus - sorry for the delay! Almost forgot about that. Commit(s) to be rebased once approved / discussed / whatever!
To …

Better `eslint` lookup

---

lib/helpers.js
lib/main.js
lib/reporter.js
lib/worker-helpers.js
lib/worker.js
package.json
src/helpers.js
src/main.js
src/reporter.js
src/worker-helpers.js
src/worker.js

Changes so far
- Log stuff to console as recieved instead of on exit
- Remove timeout from worker spawn
- Use module.exports instead of exports because babel 6's es6 default export is incompatible with commonjs
Fixes #364
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/373)

Cleanup the codebase

---

circle.yml

Not all mirrors are serving the older package versions, so the builds are failing due to 404s.
See an example here: https://circleci.com/gh/AtomLinter/linter-eslint/292
This issue has only affected a few builds so far, but will get worse and worse as the mirrors diverge more from what the old database on the CircleCI containers are expecting.

Force an apt update

---

lib/helpers.js
lib/main.js
lib/worker-helpers.js
lib/worker.js
package.json

Pin the eslint version as a few other bugs are being held back in diagnosis due to CI failing. If users need a newer version one locally installed in their project will work.
This can be removed once `babel-eslint` and `eslint@2.3.0` figure out what they are going to do...

Pin eslint version

---

lib/helpers.js
lib/main.js
src/helpers.js
src/main.js

User can now click the rule name to view the rule on the eslint website in their browser.
The only issue is the color of the rule at the cursor, but that should probably be fixed in `linter-ui-default`, not here.

Feat link to rule definition

---

lib/worker-helpers.js
src/worker-helpers.js

Fixes #448 
I honestly have no idea why ESLint is not finding the `.eslintignore` file on its own sometimes.  Sometimes it does, and sometimes it doesn't.  With these changes, if we find a `.eslintignore` file, we will pass it to ESLint with the `--ignore-path` arg, to be sure it's picked up.

Pass ignore file to eslint explicitly

---

lib/main.js
spec/linter-eslint-spec.js
src/main.js

~~**DO NOT MERGE** 
Need to fix the unit test . I could not figure out how to write the unit test which checks something after the file is saved. I used setTimeOut as an ugly hack , but somone please help.~~
I wish to handle unit tests in another task if its fine. Otherwise we can keep this pull request open for a while till we can get the unit test . 
**Main change** : 
1. Added new option (`boolean`) to check if we need to fix the errors on save. Default is `false`
2. Everytime a file is opened, an observer to save event is added, on save we check if config is true then call fix errors job
3. If fixing is success, we stay quiet . If an exceptions happens, we report .

Add `Fix on Save option` to fix lint errors on save ( fixes #417)

---

lib/reporter.js
lib/worker-helpers.js
package.json
spec/.eslintrc
spec/common.js
spec/fixtures/files/good.js
src/reporter.js
src/worker-helpers.js

Move to `eslint-config-airbnb-base` from `eslint-config-airbnb` as we don't need the React related stuff.
Updates the minimum Atom version to v1.4.0 so the `Object.assign()` polyfill can be removed. This could probably be earlier, but is there any reason to go further back?
Closes #540.
Closes #547.

Move to eslint-config-airbnb-base

---

lib/main.js
src/main.js

We already have valid scopes listed as 
```js
this.scopes = ['source.js', 'source.jsx', 'source.js.jsx', 'source.babel', 'source.js-semantic']
```
I am using the same array and comparing if the file type belongs to one of them .
With this fix, it is not running in all file types. 
Please validate.

Fix: 'Fix on Save' should run only in valid file types

---

lib/helpers.js

This makes the link to rule documentation work for the plugins used by the airbnb preset.

Add URIs for documentation of plugins

---

lib/helpers.js
src/helpers.js

I merged #562 too quickly before realizing that there were no `src` file
changes, only changes to `lib`, which would have been overwritten the
first time someone else compiled `src` to `lib`.  This commit brings
@relekang’s contribution over to the `src` file with a few minor
modifications to meet our linting rules.

Add plugin rule switch statement to src

---

lib/main.js
src/main.js

As brought up in https://github.com/AtomLinter/linter-eslint/issues/548, `Disable using .eslintignore files` is very ambiguous. It's not clear whether checking the box will "Disable (the use of) .eslintignore files," (which is actually what it's doing) or whether checking the box will "Disable (this package) using .eslintignore files" (which makes it appear to be a bug when this box isn't checked but the package still obeys `.eslintignore` files).

Clarified disableEslintIgnore description

---

lib/helpers.js
src/helpers.js

All AVA-related projects moved to a new organization named `avajs`, including this plugin. There is a redirection, but this should be better.

Update `eslint-plugin-ava` repository link

---

lib/main.js
package.json
src/main.js

This PR will allow the user to add or remove scopes that will apply to `linter-eslint`.  The primary reason I am submitting this PR is for https://github.com/rtsao/csjs and by proxy https://github.com/neurosnap/language-csjs which will allow us to extend the linter to this pseudo language.

Make scopes a configuration setting

---

lib/worker.js
src/worker.js

Addresses AtomLinter/linter-eslint#669

Supress warnings about the current file being ignored by eslint

---

lib/main.js
src/main.js

When the TextEditor contents have been modified since the initial lint() was triggered, simply return `null` instead of trying to parse the results as the current text is no longer valid for positioning markers at.
Note that returning `null` makes Linter ignore the `lint(0` results, leaving the current messages untouched. Atom itself will have handled keeping old markers aligned with the text (if possible).
The worst case for the changes this PR introduces is that it might introduce a slightly longer delay between when a change is made in the document and lint results updating as any lint that has the text modified underneath it will simply stop processing.
There is _technically_ still a slight chance that a race condition could happen between the check introduced here and finishing …

Handle modified editor race conditions

---

package.json
spec/.eslintrc.js
spec/fixtures/configs/.eslintrc.yml
spec/linter-eslint-spec.js

While looking into the spec failures currently being experienced in https://github.com/AtomLinter/linter-eslint/pull/666, I noticed that some specs were failing which weren't directly related to the changes in that PR.  I found the specs to be failing for me locally as well, so this is an attempt to clean them up and get master to a good, passing state.

Fix Failing and Flakey "Fix" Specs

---

lib/main.js
lib/worker-helpers.js
lib/worker.js
spec/fixtures/global-eslint/node_modules/eslint/lib/cli.js
spec/linter-eslint-spec.js
spec/worker-helpers-spec.js
src/main.js
src/worker-helpers.js
src/worker.js

This PR adds a `Linter Eslint: Debug` command which will pop open a notification with some useful debugging information including various package versions, the type of ESLint is being used for the current file, the linter-eslint configuration, time since the last atom restart, and more.  
My intent is to add an issue template which asks users to provide the output of this command, to assist package maintainers in troubleshooting and triaging incoming issue reports.
Example output:

Add debug command

---

lib/helpers.js
lib/main.js
spec/fixtures/end-range/.eslintrc.js
spec/fixtures/end-range/no-unreachable.js
spec/linter-eslint-spec.js
src/helpers.js
src/main.js

In https://github.com/eslint/eslint/pull/6640, released in `eslint@3.1.0`, ESLint added the ability for a rule to return a full range instead of just a single point. This PR adds support for that.
Merging of this is currently blocked however as no core rule currently actually returns a range (https://github.com/eslint/eslint/issues/3307), so we have nothing to validate against.

Add support for endLine and endColumn

---

package.json

As ESLint is not only a dependency of this project, but also used for developing it, it should have been listed in here from the start. Brought to the forefront by https://github.com/atom/ci/pull/60 as we discovered that linting wasn't actually running on the CI builds.

Add ESLint to the devDependencies

---

lib/helpers.js
lib/main.js
lib/worker-helpers.js
lib/worker.js
spec/linter-eslint-spec.js
src/helpers.js
src/main.js

Gracefully handle invalid points reported by ESLint, transforming them into regular Linter messages. These messages include a link to allow easy reporting of an issue to this repository.
Example of messages in the in-development Linter UI:
And the generated issue:
Fixes #735.

Gracefully handle invalid points

---

lib/main.js
lib/worker.js
spec/linter-eslint-spec.js
src/main.js
src/worker.js

Fixes #511 
This adjusts the response of running `Linter eslint: fix` or fixing automatically on save, so that unexpected runtime errors are correctly printed in a notification.
This PR also no longer treats an incomplete `fix` as requiring a warning.  A success message is given whether the fix is total or partial, with only the wording being altered to reflect the result.  As I mention in the commit message details, I believe `eslint.execute` used to throw when autofix did not fix all of the errors in a file.  It no longer does, so we need to rely on the exit code instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/777)

Determine fix results based on exit code

---

lib/main.js
package.json
spec/linter-eslint-spec.js
src/main.js

Closes #791 
This adds an option, "Disable specific rules from fixes" which allows users to specify a list of rules which should _not_ be auto-fixed by ESLint.  The option is _very_ similar to the already-existing `rulesToSilenceWhileTyping` option, and uses the same strategy of setting `--rule` to disable the specified rules.  
In the interest of simplicity and avoiding surprises, this option applies to both fixes made during saves, as well as manual fixes run from the command palette.  
The spec is largely duplicated from the existing spec for fix jobs, but it didn't make sense to me to try to abstract it out into another function.  That would just add some indirection for very little benefit, in my opinion.
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Allow rules to be excluded from fixes

---

.gitattributes

Background
----------
It appears that if any file recursively `require`d by the linter-eslint worker includes `babel/register`, then all babel configs through all parent directories of that file are processed.
Here is where `babel/register` inits `OptionManager`: https://github.com/babel/babel/blob/master/packages/babel-register/src/node.js#L51
And here is where `OptionManager` iterates parent dirs: https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/options/build-config-chain.js#L60
In #796, this happens specifically when `eslint-import-resolver-webpack` `require`s a webpack config that in turn `require`s `babel/register`.  `register` inits `OptionManager`, which in turn finds and processes all babel configs in parent dirs, and chokes when it cannot …

:bug: Exclude .babelrc from APM releases (fixes #796)

---

lib/helpers.js
src/helpers.js

Apparently for some users the `atom.packages.resolvePackagePath('linter-eslint')` command can fail to return the package path. When this happens create a fake Object setting the version to `unknown!`.
Fixes #784.

Check for undefined package path

---

lib/main.js
src/main.js

When the fixOnSave callback is ran previously we were using the file level "master scope", this fails though when the user has enabled HTML embedded JS linting. Use the cursors of the provided editor to check the valid scopes.
Fixes #794.

Use cursor scope when checking fixOnSave scopes

---

lib/helpers.js
spec/linter-eslint-spec.js
src/helpers.js
styles/atom-text-editor.less

The forced styling being done before was breaking on several themes, to the point where some were unreadable. This removes the badge styling and instead lets the theme handle the URL as a simple link. Rule name is moved to the end of the message, similar to ESLint's CLI output.
For example in my current theme this is what it looks like before this PR:
And after:
Fixes #482.

Remove custom styling

---

spec/linter-eslint-spec.js

This particular spec has been intermittently, but quite often, failing on CircleCI. Disable it till the issue can be tracked down.
Closes #800.
Closes #803.
Closes #804.

Temporarily disable a spec

---

lib/helpers.js
src/helpers.js

Display the scopes of the last cursor in the current file in the debug command so they can be verified against the scopes allowed in the configuration of the package.
Also guards against an invalid `TextEditor` somehow getting returned from `atom.workspace.getActiveTextEditor()`.

Log the file scope in debug command

---

package.json
spec/linter-eslint-spec.js

This version slightly changes how a rule we were using to test reporting of fixes reports its fixes, causing the specs to fail.

ESLint v3.17.0

---

lib/main.js
src/main.js

The cursor at the moment jumps to the beginning of the file after the fix command. It infuriates me :)

restore cursor position after fix command

---

lib/helpers.js
lib/is-config-at-home-root.js
lib/main.js
lib/worker.js
package.json
spec/linter-eslint-spec.js
src/helpers.js
src/is-config-at-home-root.js
src/main.js
src/worker.js

Reduce activation time of the package by deferring some actions for a later idle time and lazily requiring imports where possible. On my system this reduces package activation from an average of 177 ms down to 7 ms. The remaining 7 ms is largely taken up with Atom internals, with only 1.3 ms being under our control in any manner.
Fixes #871.

Reduce package activation time

---

lib/main.js
src/main.js

If the package is requested to be deactivated before a pending idle callback has ran we should cancel that callback as there is no point in running it.
Should have been part of #875, but I hadn't thought of this race condition yet 😛.

Cancel pending idle callbacks

---

package.json
spec/common.js
spec/linter-eslint-spec.js
spec/worker-helpers-spec.js

Bring in the `jasmine-fix` module and utilize the `async` compatible `beforeEach` and `it` methods it provides. Refactor the code to utilize this instead of the `waitsForPromise` method from the default
environment.
Includes several fixes to the specs:
* Introduce a `getNotification` method to grab the next Notification added to Atom, allowing situations such as waiting on the fix command.
* Re-write the `makeFixes` function so it waits on the fix command to finish, including the file changes in Atom before continuing the spec.
* Make both `fix` specs use the same functions so the code isn't duplicated.
* Utilize the `lint` function directly, using the worker spawned from the `activate` call instead of a separate one spawned in the specs.

Async-ify the specs

---

package.json

Explicitly updating to this version since it cuts the time to require this dependency by 3-4x. It's already moved to an idle callback, but why not make sure that runs as fast as possible as well? 😛

chore(package): update atom-package-deps to version 4.6.0

---

lib/worker-helpers.js
spec/fixtures/badCache/.eslintrc.js
spec/fixtures/badCache/temp/foo.js
spec/linter-eslint-spec.js
src/worker-helpers.js

ESLint already handles grabbing the configuration for a file for us, but we have actually been preventing this from working properly by always specifying the path to what we determined to be the configuration file.
Since we really only need that to determine if we should run ESLint at all, stop sending that to ESLint unless we are overriding it with a fallback.
Fixes #892.

Allow ESLint to fully determine config when possible

---

lib/helpers.js
lib/main.js
lib/worker.js
package.json
src/helpers.js
src/main.js
src/worker.js

Moves us to utilizing Atom's Task API for managing the worker process.
This provides the framework for a future PR switching to using per-package transpilation, as well as reduces the external dependencies of the project.
It also appears that this provides a slight speedup to linting as average lints for a specific file went from 115 ms down to 104 ms!

Atom Task API

---

spec/linter-eslint-spec.js
src/main.js
src/worker.js

Fixes #635 
The main point of this PR is to avoid deleting the `.eslintcache` file when performing fix jobs in `linter-eslint`.  Previously, they were deleted because if ESLint is run without the `cache` option, it will automatically delete any existing cache files.  `linter-eslint` doesn't delete the cache on regular `lint` jobs because it uses `executeOnText`, which bypasses the cache and does not delete it.  
**Update**: I've changed this PR to use `executeOnText` for fix jobs as suggested by @not-an-aardvark in https://github.com/AtomLinter/linter-eslint/pull/873#discussion_r110076641.  It's a much better solution than my first approach.
~~The approach I took was fairly simplistic.  We will search for a `.eslintcache` file, and if we find it, we will set `cache` for fix jobs.  There …

Preserve `.eslintcache` on fixes

---

spec/fixtures/global-eslint/node_modules/eslint/lib/api.js
spec/fixtures/global-eslint/node_modules/eslint/package.json
spec/worker-helpers-spec.js
src/worker-helpers.js

Add support for global Yarn installations. Apparently one of the few things Yarn did right is that all platforms use the same directory structure under the base directory, unfortunately that meant that on non-Windows platforms specifying the path still got you an unusable setup.
Also fixes the error messages that can be thrown to better reflect the actual causes of the messages.
Fixes #680.
Fixes #780.

Support global Yarn installs and better errors

---

.travis.yml

Atom v1.18.0 brings in a version of APM that requires Trusty on Travis-CI.
See https://github.com/atom/atom/issues/14440 for more details.

Fix builds of Atom beta

---

src/helpers.js

ESLint outputs context in the most recent versions which is useless inside Atom
Can be seen in a lot of issues across the repos, https://github.com/steelbrain/linter-ui-default/issues/309 is the most recent one

Handle fatal syntax errors gracefully

---

spec/linter-eslint-spec.js
src/main.js

Previously when a custom scope was edited and embedded HTML was enabled, the linting of embedded HTML would temporarily break till Atom was restarted or the embedded HTML setting was toggled off and on. This ensures the scope is in the current scope list if it is enabled.
Fixes #823.

Fix embedded HTML scope with custom scopes

---

src/worker-helpers.js
src/worker.js

Now that all execution of ESLint is being done through `executeOnText` we can move to the `warnIgnored` option instead of manually filtering out the ignore messages.
Fixes #900.

Utilize warnIgnored instead of filtering messages

---

src/main.js

Reverts #853.
From the testing done so far this code either:
* Does exactly what Atom is already doing itself if the fix doesn't replace the entire file
* Doesn't actually work if the entire file is replaced (rare to reproduce this)
So in either case the code is doing nothing but adding complexity to the codebase.

Revert #853

---

spec/linter-eslint-spec.js

Add a spec testing that the "Show Rule ID in Messages" option works as expected.
Fixes #473.

Add spec for showRuleIdInMessage

---

.gitattributes
CONTRIBUTING.md

Update the documentation for the simplified process now that the transpilation is in place. Also removes reference to the `.babelrc` file that no longer exists.

Cleanup and update the developer documentation

---

package.json

The built in transpilation was pulling in `.babelrc` files from user's machines, including locations like `~/.babelrc`. This was causing the package to not be transpiled in a manner compatible with Atom.
Fixes #920.

Prevent Atom transpilation from searching for .babelrc

---

src/worker-helpers.js
src/worker.js

Make sure that when finding the ESLint directory the projectPath variable is either set, or swapped for an empty string to prevent an error.
Closes #958.

Ensure that projectPath has a value

---

package.json

Although we aren't utilizing it, `atom-babel6-transpiler` was setting `BABEL_ENV` to `undefined` whenever this package was transpiled leading to other Atom packages that use that environment variable to become corrupted.
Fixes #921.

Force atom-babel6-transpiler to not set BABEL_ENV

---

spec/linter-eslint-spec.js
spec/worker-helpers-spec.js
src/worker-helpers.js
src/worker.js

This tweaks our fallback cwd and relative path resolution slightly, such that instead of falling straight back to just the directory of the file itself, we will use the base directory open in the atom editor.
If for whatever reason that is `null` (or undefined), we’ll still fall back to the file directory as before.
This approach was suggested in https://github.com/AtomLinter/linter-eslint/issues/827#issuecomment-281770220.
It's still possible for users to have a folder open that is _not_ their project root, in which case they might get strange results, but it is likely an improvement for the majority of users.
Closes #964

Try to set cwd to project root dir if no .eslintignore is found

---

spec/linter-eslint-spec.js
src/main.js

Add an "ESLint Fix" command to the right click menu when it is the active editor and is listed as a valid scope according to the current settings.
Fixes #955.

Add an ESLint Fix right click command

---

spec/linter-eslint-spec.js

It seems that `TextBuffer::onDidReload` isn't firing in Atom v1.19.0, disable the specs relying on that till https://github.com/atom/atom/issues/15200 is fixed in Atom.

Disable specs relying on TextBuffer::onDidReload

---

package-lock.json
src/main.js

When a fix job is triggered but the TextEditor is invalid by the time the job runs silently return.
Fixes #972.

Ignore invalid TextEditors for fix jobs

---

spec/linter-eslint-spec.js

It turns out that `TextBuffer::onDidReload` is being broken _only_ in the specs, as it relies on `Date.now()` which Jasmine was mocking. We can fix this by telling Jasmine to stop spying on that function.
Also re-enables a long-disabled test that looks to be working properly now that the `TextBuffer` rewrite has landed.

Disable spying on Date.now by Jasmine

---

package-lock.json
package.json
spec/linter-eslint-spec.js

The links to `eslint.org` returned from this package were recently updated to use `https`, update the specs accordingly and set a new minimum version.

Update `eslint-rule-documentation` to version 1.0.18

---

spec/linter-eslint-spec.js

Removes some uses of -new Promise- and -async/await- that do not serve any real purpose because underlying function calls already return promise

remove superfluous async & Promise from some specs

---

spec/linter-eslint-spec.js
src/helpers.js
src/main.js

Translate all errors coming from ESLint into a lint message instead of throwing them out to be caught by Linter's generic error catching mechanism. This allows us to present them in a much cleaner manner and
gives the user immediate feedback on what is going wrong.
Also includes several cleanups related to error handling to get a more unified experience with errors.
Errors were only shown as an Atom error notification from Linter's generic catch-all:
Repeated lint requests would spam the message on the user's screen, providing a rather poor experience.
Errors coming from ESLint will show as a message in Linter, with the expandable message details showing the full stack trace:
Linter message:
Full details:
Fixes #387.

Handle errors as a lint message

---

package.json
spec/fixtures/modified-ignore-rule/.eslintrc.js
spec/fixtures/modified-ignore-rule/foo-space.js
spec/fixtures/modified-ignore-rule/foo.js
spec/fixtures/plugin-import/.eslintrc.js
spec/fixtures/plugin-import/life.js
spec/fixtures/plugin-import/meaning.js
spec/linter-eslint-spec.js
src/helpers.js
src/main.js
src/worker.js

Add an option that silences fixable rules while typing. The list of fixable rules is populated from ESLint itself, and only sent back to the main package code when it updates to reduce message size. This means that this will only start silencing rules after the first lint rule. Since a lint is triggered on open by default this _should_ be largely transparent to the user.
Fixes #894.

Add option to silence fixable rules while typing

---

package.json
src/worker.js

ESLint below v4 doesn't support the necessary version of the ESLint `Linter` API to allow grabbing the fixable rules. When running with an ancient version of ESLint simply don't process fixable rules.
Fixes #1021.

Don't attempt to process fixable rules on ESLint v3

---

src/main.js

Atom has started showing a deprecation warning for the Atom v1.18.0 style check done for the context menu. Remove this check making the context menu now only show on Atom v1.19.0 and above.

Fix deprecation warning in Atom v1.21.0

---

src/worker.js

Verify that a rule has a `meta` property before attempting to access it to see if the rule is fixable or not.
Fixes #1023.

Verify that a rule has a meta property before accessing

---

package-lock.json
package.json
src/worker-helpers.js

Enhance all paths in the configurations so that they allow the use of `~` where appropriate.
Fixes #985.

Normalize all config paths

---

src/helpers.js
src/main.js

Add several sanity checks before moving on to attempting to lint the file:
* Check that the `TextEditor` is valid
* Check that the path for the file is not empty
* Check that the path isn't a remote path
If a remote path is found, show a message to the user that linting isn't possible.
Blocked on #1015 as it uses the Error handling functionality introduced in that branch. Just putting this up here so it can get reviewed.
Fixes #594.

Check for remote files

---

package.json
src/main.js
src/worker-helpers.js

Replace the `eslintRulesDir` option with a new `eslintRulesDirs` option that is an Array of directories that are passed to ESLint.
Fixes #321.

Allow multiple rule directories

---

src/worker-helpers.js

This flag has no meaning to the `CLIEngine` constructor, it is only valid as an optional third argument to `executeOnText`. When this was mistakenly added in https://github.com/AtomLinter/linter-eslint/pull/915 this was missed. Luckily the problem it was meant to solve was accepted as a bug against ESLint itself and fixed there which is why this wasn't caught earlier.

Remove definition of warnIgnored in CLIEngine options

---

spec/linter-eslint-spec.js

The makeFixes function is now properly determinent, as a consumer cannot
receive a resolved promise before all lines of makeFixes have executed.
This might (appears to so far) resolve problems with flaky specs.

Don't return promise until makeFixes completes

---

src/helpers.js
src/main.js
src/worker.js

Refs #925 #927 #930 #1059
This is an attempt to mitigate some of the problems being experienced in the referenced issues, whereby linter-eslint crashes/hangs with a high memory usage.
I was unable to determine the exact cause of workers dying, but this PR does a few things to try to minimize the crashes and memory usage, as well as allowing linter-eslint to recover from a crashed worker.  In one of my projects, I was able to reliably reproduce the crashes, usually within a few seconds of opening a file.  Using this branch, linter-eslint has now become usable for me again, albeit during a crash it still takes a few seconds to recover and start working again, so I don't consider this a complete solution.
I think the main challenge we are facing is that the Task api from Atom is not intended …

Handle worker crashes

---

package-lock.json
package.json

Brings in a few bug fixes to the minimum version allowed.

Update atom-babel6-transpiler to v1.1.3

---

package-lock.json
package.json

Switch to using `babel-preset-env` instead of `babel-preset-node5`. This allows our transpilation to [dynamically adapt](https://www.npmjs.com/package/babel-preset-env#targetsnode) to the currently running version of Node.js within Atom instead of being forced down to Node.js v5.

Switch to babel-preset-env

---

spec/rules-spec.js
src/rules.js

Remove the validation code for the rules, the rest of the code is written with no assumptions about the content of the rules so it isn't actually necessary. Some older versions of ESLint also break some expectations that were written into it as well.
@IanVS This should fix the issue you discovered on ESLint v4.3.0.

Remove validation of rules

---

src/rules.js

Ensure that the rule actually has properties before attempting to check the `meta` property of them.

Check if the rule properties exist before checking for meta

---

CONTRIBUTING.md

Document use of `apm link` and `atom -d` for running the working directory as a package. Add some extra detail and fun to other steps. Add spacing to lists for readability.

Docs: Explain Developer Mode for contributors.

---

package-lock.json
package.json
spec/f-utils/deep-diff-dict-spec.js
spec/f-utils/f-utils-spec.js
src/f-utils/deep-diff-dict.js
src/f-utils/index.js
src/f-utils/mini-ramda.js

Adds ramda dependency with a file to map small subset to a namespaced
import. Adds fast-deep-equal. Adds several small generic functionaly
utility functions with specs to verify their behavior. Anything in this
commit not in use by the next planned release should be deleted until
proven necessary.

Update: Add ramda, fast-deep-equal, generic utils

---

src/main.js

Add an idleCallback loader that respects deadline from scheduler, requesting new idleCallback when out of time. Use idleCallbacks to lazy require packages only for caching purposes, rather than saving to variables. Use disposables interface for disposing of idleCallbacks. Add small makeCompositeDisposable function to avoid requiring from 'atom' to get the built-in class.

Respectful idleCallback loader and small CompositeDisposable

---

package-lock.json
package.json
spec/linter-eslint-spec.js

Update the version of `eslint-plugin-import` used internally in the specs to the one that is installed by `apm` (which ignores `package-lock.json` currently), also updates the specs to accommodate the changes in the latest version.

Fix CI builds

---

package.json

Everything appears to work as expected with experimental tree-sitter parser. This adds the new scope name to default scopes array.

Add 'javascript' scope by default

---

package.json

This reverts commit 1f2186ce29ddc1e503f13ad4cd7e3c9425100dd5.
Tree sitter now uses the regular TextMate based scopes, so this is not required and could be confusing.

Revert "Add 'javascript' scope by default"

---

package-lock.json
package.json

Pin the version of the dependencies that would have been installed via the old ranges if the `package-lock.json` wasn't present. Future updates to dependencies will ensure the `package-lock.json` stays consistent now, so we don't have things becoming out of date in the version that is getting installed without us realizing it.
Since Atom is now respecting `package-lock.json` this is an issue that we need to solve.
Note, this _should_ have been part of https://github.com/AtomLinter/linter-eslint/pull/1179, but it wasn't caught that that had only done the `devDependencies` when it was merged.

Pin Dependencies

---

package.json

Recent versions of atom do not add `source.js` in addition to `source.flow`,
treating flow as a completely different grammar from javascript, it seems.
This broke linting (along with other things) for flow users, unless
they added the flow source back to their config.  Instead, I think we should allow `linter-eslint` to "just work" for flow as well as regular javascript, which this
change will do.

Add source.flow to default scopes

---

spec/linter-eslint-spec.js
src/helpers.js

Fixes #1197, #1196, #1195, #1192 
The JSDoc plugin returns `null` when there isn't a end column. The ESLint API docs specifically say the type of `endColumn` and `endLine` are optional or must be a `number`, therefore it is probably more correct and safer to do that check instead of a undefined check: https://eslint.org/docs/developer-guide/working-with-plugins

Fix behavior when endColumn or endLine is null

---

package.json
spec/linter-eslint-spec.js

This speeds up loading of Atom, by deferring the loading of linter-eslint until the core Atom shell is loaded.

add activation hook

---

.github/workflows/CI.yml
package.json
spec/worker-helpers-spec.js
src/worker-helpers.js

- This improves the message of error for missing Global Eslint. 
- Adds a warning in the config for using this option.
- Makes the option collapsed in the settings view.
Take 2 of #1370. @Arcanemagus I edited the PR based on [your feedback](https://github.com/AtomLinter/linter-eslint/pull/1370#issuecomment-717557496).

Global Eslint improvements

---

README.md

I was scratching my head playing with `eslintrc` trying to figure why it wouldn't work, then I realized I had to add it to the scopes list when I stumbled on https://github.com/AtomLinter/linter-eslint/issues/1122

chore(readme): add info on linting other file types

---

package.json

We always test on the latest version, so we can't guarantee that the latest version of linter-eslint works on the older versions.
If someone insists on using an outdated version of the Linter package, they need to downgrade linter-eslint

fix: require an up to date Linter package

---

spec/worker-helpers-spec.js
src/worker-helpers.js

This fixes a StackOverflow that happened because of missing `return`. Also, now the errors are pushed to the user.
Open a .js + .eslintrc.json file in an empty folder, and enable globalEslint config (assuming you don't have eslint installed globally)

fix: fix stackoverflow for fallbackForGlobal error

---

src/helpers.js

This fixes the error itself. But the Fix button doesn't work. At least better than nothing for now.
Fixes https://github.com/AtomLinter/linter-eslint/issues/1249

fix: handle prettier line-ending issue

---

package.json
pnpm-lock.yaml
spec/fixtures/import-resolution/.eslintrc.yaml
src/rules.js
src/worker-helpers.js

This cherry-picks the changes from #1360 that do not depend on the version of Eslint. This makes it easier to fix the failing tests in #1360

Cherry-pick version agnostic changes from #1360
