lib/linter-eslint.coffee

Get CLIEngine to load plugins

---

package.json

update eslint version

---

README.md
lib/init.coffee
lib/linter-eslint.coffee

@iam4x here ya go - new mergeable version with config option :)

Allow using global eslint and plugins via togglable config option

---

lib/linter-eslint.coffee

@iam4x a small fix for plugins loading and global eslint

Fix loading plugins while using globally installed eslint

---

lib/linter-eslint.coffee

This hopefully fixes #97, #99, #100, #101, #102, #103.
I say hopefully - I've just copied the code that @aruberto commented about here: https://github.com/AtomLinter/linter-eslint/issues/99#issuecomment-112214088.
I've tried it on my machine and it seems to work - but no formal testing done.
@iam4x suggested this be made into a PR, so here it is!

Fix unsafe code within eslint.

---

lib/linter-eslint.coffee

Only add the eslint-plugin- prefix if it's missing

---

lib/linter-eslint.coffee

Build relative path using filePath rather dirname

---

lib/linter-eslint.coffee

Fixes a (very) minor typo.
Keep up the good work! I stopped counting how many hours this plugin has saved me…

Fix typo in error message

---

README.md

fix localy -> locally typo

---

lib/linter-eslint.coffee

Obtain error column from eslint

---

lib/linter-eslint.coffee

Closes https://github.com/AtomLinter/linter-eslint/issues/223

Fix column offset

---

lib/linter-eslint.coffee

Add another JSX grammar scope

---

lib/helpers.js
lib/main.js
lib/worker.js
package.json

It makes it a lot easier to debug the worker
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/264)

Handle worker termination

---

CHANGELOG.md
lib/worker.js

Fixes #259
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/266)

Support local eslint

---

lib/worker.js
package.json

Implements support for global ESLint in windows #261
OSX Support still unconfirmed
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/271)

Support global ESLint on windows

---

CHANGELOG.md
lib/worker.js

Just like the diff says
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/272)

Improve error verbosity

---

CHANGELOG.md
lib/main.js
lib/worker.js

This PR re-implements `globalNodePath`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/274)

Add globalNodePath config

---

CHANGELOG.md
lib/helpers.js
lib/main.js

Fixes #284
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/285)

Respawn worker if it crashes

---

CHANGELOG.md
lib/main.js
lib/worker.js

Fixes #281
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/286)

Add eslintRulesDir config

---

CHANGELOG.md
lib/main.js

Fixes https://github.com/AtomLinter/linter-eslint/issues/214

Add fix command

---

.travis.yml
appveyor.yml
circle.yml
package.json

Add configurations for:
* Travis-CI (OS X)
* Circle-CI (Ubuntu)
* AppVeyor (Windows)

Add CI Configurations

---

CHANGELOG.md
lib/worker.js

Support File Formats

---

package.json

Fixes #320
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/323)

Upgrade atom-package-deps

---

.ucompilerrc
lib/helpers.js
src/es5-helpers.js
src/helpers.js
src/main.js
src/reporter.js
src/worker.js

Changes in this PR:
- Moved all files from `lib` folder to `src` changing nothing in them at all
__Note:__ I've only added `.ucompilerrc` for personal use, I haven't added it as a `devDependency` because I like how I can just do `ucompiler watch src` and it'll compile all files that change with babel and save them as specified in the configuration file :stuck_out_tongue: 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/368)
This PR is targeted to be merged in #367

ES6: Add skeleton

---

README.md

https://github.com/AtomLinter/linter-eslint/issues/378#issuecomment-166166366
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/381)

Add instructions for getting started with JSLint

---

CHANGELOG.md
lib/main.js

Fixes #333
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/386)

Remove worker on timeout

---

CHANGELOG.md
lib/worker-helpers.js
package.json
src/worker-helpers.js

Fixes https://github.com/AtomLinter/linter-eslint/issues/410
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/411)

Use consistent-path when executing npm

---

CONTRIBUTING.md
README.md
package.json

This PR adds the necessary `devDependencies`, and documents the build procedure for the transpiled code.
@nmote this is what we were talking about.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/412)

Document build procedure

---

src/worker-helpers.js

It had caused confusion in #296
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/atomlinter/linter-eslint/432)

Clarify a note

---

.travis.yml
appveyor.yml
circle.yml
lib/reporter.js
lib/worker-helpers.js

This update mainly just starts Travis-CI testing the beta channel, as well as building on Linux.

Udpate CI Configuration

---

CHANGELOG.md
lib/main.js
src/main.js
styles/atom-text-editor.less

Tested in the few themes I had, looks good

Fix link style

---

CONTRIBUTING.md

After my fiasco trying to release a patch version of this package, I thought I'd throw together a quick guide.

Add release guide

---

CONTRIBUTING.md

Suggest me better phrase if this does not look good.

Adding slack link to Contributions page

---

lib/main.js
package.json
src/main.js

See https://github.com/AtomLinter/Meta/issues/12 for more details.

Move to a configuration schema in package.json

---

lib/worker-helpers.js
src/worker-helpers.js

Convert null to empty string inside path.dirname()

---

CONTRIBUTING.md
README.md

This was what was missing based on my experiences with https://github.com/AtomLinter/linter-eslint/pull/694. Anything else I should add?

Updated CONTRIBUTING.md for build process

---

lib/main.js
spec/linter-eslint-spec.js
src/main.js

* Properly activate the package in the specs
* Update the expected values now that the defaults are getting applied like they should be
* Pull scopes variable up to the file level

Fix up a few bugs in the specs

---

lib/main.js
src/main.js

There is no need to get this configuration each run.

Observe showRuleIdInMessage

---

lib/worker-helpers.js
src/worker-helpers.js

Don't specify rulesDir if not found

---

spec/linter-eslint-spec.js

As the specs execute asynchronously, it's possible for there to be more than one Notification observer active at a time, leading to some specs intermittently failing when they grab the "wrong" notification. Enhance the function that waits on a notification to check for an expected message as well, and silently discard the received notification if it doesn't match what the spec is looking for.

Wait on specific Notification in specs

---

.travis.yml
spec/linter-eslint-spec.js

Several updates to the Travis CI configuration, bringing it in line with the current state of `atom/ci` and fixing Atom Beta builds.

Update Travis CI configuration

---

package-lock.json
package.json
spec/linter-eslint-spec.js

`jasmine-fix@^1.3.0` does this for us, meaning that our attempt to do so was now breaking things.

Stop disabling spying of Date.now

---

spec/linter-eslint-spec.js

Each fixture is defined as an object property. Fixture value is an array of path.join arguments excluding fixtureDir. This object is then reduced to prepend fixtureDir and join with path.join. Path can be used by referencing property of paths, i.e. paths.badInline.

make fixtures path definitions prettier and simpler to write

---

spec/linter-eslint-spec.js

Fix a small spelling error in one of the comments.
Fixes #1030.

Fix a comment typo

---

src/main.js

Use requestAnimationFrame to queue up dependency loading at first available future opportunity.

Late require dependencies

---

src/main.js

Merge the list of rules from `ignoreFixableRulesWhileTyping` and `ignoredRulesWhenModified` into a single list that is sent to ESLint.
Fixes #1081.

Merge all rules to ignore while typing

---

src/helpers.js
src/main.js

The `worker` was getting passed around as a parameter to nearly every `helpers` function only because it was being maintained in the main class. Move the `worker` into the helpers module and simply expose a function to kill it as that was the main state needed in `main.js`.

Move worker management to the helpers module

---

package-lock.json
package.json
spec/f-utils/deep-diff-dict-spec.js
spec/f-utils/f-utils-spec.js
src/f-utils/deep-diff-dict.js
src/f-utils/index.js
src/f-utils/mini-ramda.js

Add ramda, fast-deep-equal, a few generic utils (2)

---

spec/make-spy.js
spec/validate/editor-spec.js
spec/validate/throw-spec.js
src/helpers.js
src/main.js
src/validate/editor.js
src/validate/throw.js

Move validation of TextBuffer points and editor scopes to a separate
files in  folder dedicated to validation logic..

Update: Extract some validation to separate files

---

package-lock.json
package.json

Remove dependency with no obvious benefit over built-in transpiler.

Remove babel6 transpile dependency

---

package.json

Add a basic configuration for the Renovate dependency management tool that extends its default values.

Add configuration for Renovate

---

.circleci/config.yml
.travis.yml
package-lock.json
package.json

Add [commitlint](http://marionebl.github.io/commitlint) as well as a [Conventional Commits](https://www.conventionalcommits.org/) based configuration to enforce commit messages are always in a consistent format.

Add commitlint

---

package.json
pnpm-lock.yaml
src/helpers.js

This fixes an error caused by Crypto API change.

fix: expected a `length` to be non-negative error

---

src/rules.js

This makes Rules class simpler and faster

improve Rules in src/rules.js

---

.github/workflows/CI.yml

This will make it easier to know if it is the code or commit message that needs to be changed.

chore(ci): separate commitlint from lint

---

.eslintignore
package.json
pnpm-lock.yaml
spec/fixtures/import-resolution/.eslintrc.yaml

updating eslint will take some work but I figured we might as well update the other dependencies

fix(deps): update atom-package-deps

---

.eslintignore
.github/workflows/CI.yml
.gitignore
babel.config.json
package.json
pnpm-lock.yaml
rollup.config.js
spec/linter-eslint-spec.js
spec/migrate-config-options-spec.js
spec/rules-spec.js
spec/validate/editor-spec.js
spec/validate/throw-spec.js
spec/worker-helpers-spec.js
src/helpers.js
src/main.js
src/migrate-config-options.js
src/validate/editor.js
src/validate/throw.js
src/worker-helpers.js
src/worker.js

Closes #1245 
This also speeds up the loading time by 2 times!
After
Before
Also, no longer the users need to run babel on their machines for the first load:

chore: update babel 
